name: Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: codebuild-terraform-github-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: execute echo command
        run: echo "Hello World!"
